# Site settings
title: Truong Ngoc Hieu
email: hieu.tnbk2011@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  I appreciate your taking the time to review my Resume and answers. Again, thank you for your consideration. I will try my best to working hard and bring the my best support experience to your customer.
baseurl: "" # the subpath of your site, e.g. /blog/
github_username:  hieu.tnbk2011

# Build settings
markdown: kramdown
include: [_redirects]
